# Generated by Django 5.0.9 on 2024-11-25 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Required for age-appropriate session recommendations', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Name of person to contact in case of emergency', max_length=255, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Phone number of emergency contact', max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', help_text='Enter your first name', max_length=150, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', help_text='Enter your last name', max_length=150, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for important notifications', max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text='Preferred language for communications', max_length=10, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications about sessions and updates', verbose_name='Receive Notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Your email address will be used for login and communications', max_length=254, unique=True, verbose_name='Email Address'),
        ),
    ]
