# Generated by Django 5.0.9 on 2024-11-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_proposal_institution_alter_proposal_options_and_more'),
        ('users', '0002_alter_user_options_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Associated organization or company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='services.organization', verbose_name='Organization'),
        ),
    ]
