# Generated by Django 5.0.9 on 2025-02-19 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0005_servicepackage_discount_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the package', max_length=100)),
                ('total_sessions', models.PositiveIntegerField(help_text='Total number of sessions in the package')),
                ('used_sessions', models.PositiveIntegerField(default=0, help_text='Number of sessions already used')),
                ('expiry_date', models.DateField(help_text='Date when the package expires')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the package was purchased')),
                ('active', models.BooleanField(default=True, help_text='Whether this package is currently active')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization if this is a corporate package', null=True, on_delete=django.db.models.deletion.PROTECT, to='services.organization')),
                ('owner', models.ForeignKey(help_text='User who owns this package', on_delete=django.db.models.deletion.PROTECT, related_name='package_instances', to=settings.AUTH_USER_MODEL)),
                ('service_package', models.ForeignKey(help_text='Service package template this package is based on', on_delete=django.db.models.deletion.PROTECT, related_name='purchased_packages', to='services.servicepackage')),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, help_text='Date when package was assigned')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the assignment')),
                ('assigned_by', models.ForeignKey(help_text='User who assigned the package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_assignments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client assigned to this package', on_delete=django.db.models.deletion.PROTECT, related_name='client_packages', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(help_text='Package assigned to the client', on_delete=django.db.models.deletion.PROTECT, related_name='client_assignments', to='packages.package')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['expiry_date'], name='packages_pa_expiry__df6714_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['active'], name='packages_pa_active_977132_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['purchase_date'], name='packages_pa_purchas_ef66ab_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpackage',
            index=models.Index(fields=['assigned_date'], name='packages_cl_assigne_29475d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientpackage',
            unique_together={('client', 'package')},
        ),
    ]
