# Generated by Django 5.0.9 on 2024-11-26 12:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the corporate program', max_length=200, verbose_name='Program Name')),
                ('description', models.TextField(help_text='Detailed description of the program', verbose_name='Description')),
                ('duration_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='annual', max_length=20, verbose_name='Duration Type')),
                ('assessment_frequency', models.PositiveIntegerField(default=90, help_text='Frequency of assessments in days', verbose_name='Assessment Frequency (days)')),
                ('max_participants', models.PositiveIntegerField(default=100, help_text='Maximum number of participants allowed', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Participants')),
                ('features', models.JSONField(default=list, help_text='List of features included in this program', verbose_name='Program Features')),
            ],
            options={
                'verbose_name': 'Corporate Program',
                'verbose_name_plural': 'Corporate Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the service', max_length=200, verbose_name='Name')),
                ('description', models.TextField(help_text='Detailed description of the service', verbose_name='Description')),
                ('duration', models.PositiveIntegerField(help_text='Duration of the service in minutes', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)], verbose_name='Duration (minutes)')),
                ('max_participants', models.PositiveIntegerField(default=1, help_text='Maximum number of participants allowed', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Maximum Participants')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this service', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base Price')),
                ('prerequisites', models.TextField(blank=True, help_text='Any prerequisites or requirements for this service', verbose_name='Prerequisites')),
                ('target_areas', models.TextField(blank=True, help_text='Specific areas or benefits targeted by this service', verbose_name='Target Areas')),
                ('is_corporate_eligible', models.BooleanField(default=False, help_text='Whether this service can be included in corporate packages', verbose_name='Corporate Eligible')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Category name (e.g., "25min Stretch", "Corporate Wellness")', max_length=100, verbose_name='Name')),
                ('description', models.TextField(help_text='Detailed description of this service category', verbose_name='Description')),
                ('type', models.CharField(choices=[('individual', 'Individual Services'), ('group', 'Group Services'), ('corporate', 'Corporate Services'), ('therapeutic', 'Therapeutic Services')], default='individual', max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the institution', max_length=200, verbose_name='Institution Name')),
                ('industry', models.CharField(help_text='Industry sector of the institution', max_length=100, verbose_name='Industry')),
                ('contact_email', models.EmailField(help_text='Primary contact email', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(help_text='Primary contact phone number', max_length=20, verbose_name='Contact Phone')),
                ('address', models.TextField(help_text='Physical address of the institution', verbose_name='Address')),
                ('employee_count', models.PositiveIntegerField(help_text='Total number of employees', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Employees')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='Contract Start Date')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Contract End Date')),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements or notes', verbose_name='Special Requirements')),
                ('active_programs', models.ManyToManyField(blank=True, related_name='institutions', to='services.corporateprogram', verbose_name='Active Programs')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Title of the proposal', max_length=200, verbose_name='Title')),
                ('date_submitted', models.DateField(blank=True, null=True, verbose_name='Date Submitted')),
                ('custom_services', models.TextField(blank=True, help_text='Any custom services offered in this proposal', verbose_name='Custom Services')),
                ('pricing_details', models.JSONField(default=dict, help_text='Detailed pricing information', verbose_name='Pricing Details')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('valid_until', models.DateField(help_text='Date until which this proposal is valid', verbose_name='Valid Until')),
                ('terms_conditions', models.TextField(help_text='Terms and conditions of the proposal', verbose_name='Terms and Conditions')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='services.institution', verbose_name='Institution')),
                ('programs', models.ManyToManyField(related_name='proposals', to='services.corporateprogram', verbose_name='Offered Programs')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='corporateprogram',
            name='services',
            field=models.ManyToManyField(limit_choices_to={'is_corporate_eligible': True}, related_name='corporate_programs', to='services.service', verbose_name='Included Services'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the package', max_length=200, verbose_name='Package Name')),
                ('package_type', models.CharField(choices=[('individual', 'Individual Package'), ('corporate', 'Corporate Package')], default='individual', max_length=20, verbose_name='Package Type')),
                ('number_of_sessions', models.PositiveIntegerField(help_text='Number of sessions included in this package', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Sessions')),
                ('validity_period', models.PositiveIntegerField(help_text='Number of days this package is valid for', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Validity Period (days)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage for this package', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage')),
                ('terms_conditions', models.TextField(help_text='Terms and conditions for this package', verbose_name='Terms and Conditions')),
                ('features', models.JSONField(default=list, help_text='List of features included in this package', verbose_name='Package Features')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['service', 'name'],
            },
        ),
    ]
