# Generated by Django 5.0.9 on 2024-11-26 14:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='institution',
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-date_submitted'], 'verbose_name': 'Proposal', 'verbose_name_plural': 'Proposals'},
        ),
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='custom_services',
            field=models.TextField(blank=True, help_text='Description of any custom services offered', verbose_name='Custom Services'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_submitted',
            field=models.DateTimeField(blank=True, help_text='Date when the proposal was submitted', null=True, verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pricing_details',
            field=models.TextField(help_text='Detailed pricing information', verbose_name='Pricing Details'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='programs',
            field=models.ManyToManyField(help_text='Corporate programs included in this proposal', to='services.corporateprogram', verbose_name='Programs'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', help_text='Current status of the proposal', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the organization', max_length=200, verbose_name='Organization Name')),
                ('industry', models.CharField(help_text='Industry sector of the organization', max_length=100, verbose_name='Industry')),
                ('contact_email', models.EmailField(help_text='Primary contact email', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(help_text='Primary contact phone number', max_length=20, verbose_name='Contact Phone')),
                ('address', models.TextField(help_text='Physical address of the organization', verbose_name='Address')),
                ('employee_count', models.PositiveIntegerField(help_text='Total number of employees', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Employees')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='Contract Start Date')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Contract End Date')),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements or notes', verbose_name='Special Requirements')),
                ('active_programs', models.ManyToManyField(blank=True, related_name='organizations', to='services.corporateprogram', verbose_name='Active Programs')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='services.organization', verbose_name='Organization'),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
