# Generated by Django 5.0.9 on 2024-11-27 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_proposal_institution_alter_proposal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(help_text='Primary contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must start with + followed by at least 10 digits.', regex='^\\+\\d{10,}$')], verbose_name='Contact Phone'),
        ),
    ]
