# Generated by Django 5.0.9 on 2025-02-15 07:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_organization_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='base_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='servicepackage',
            old_name='number_of_sessions',
            new_name='sessions',
        ),
        migrations.RemoveField(
            model_name='corporateprogram',
            name='assessment_frequency',
        ),
        migrations.RemoveField(
            model_name='corporateprogram',
            name='duration_type',
        ),
        migrations.RemoveField(
            model_name='corporateprogram',
            name='features',
        ),
        migrations.RemoveField(
            model_name='service',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='service',
            name='target_areas',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='features',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='terms_conditions',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='validity_period',
        ),
        migrations.AddField(
            model_name='corporateprogram',
            name='min_participants',
            field=models.PositiveIntegerField(default=5, verbose_name='Minimum Participants'),
        ),
        migrations.AddField(
            model_name='service',
            name='home_visit_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional charge for home visits', max_digits=10, verbose_name='Home Visit Surcharge'),
        ),
        migrations.AddField(
            model_name='service',
            name='supports_home_visits',
            field=models.BooleanField(default=False, help_text="Whether this service can be provided at client's home", verbose_name='Supports Home Visits'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='price_per_session',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Price per Session'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='validity_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days the package is valid for', verbose_name='Validity Period'),
        ),
        migrations.AlterField(
            model_name='corporateprogram',
            name='max_participants',
            field=models.PositiveIntegerField(default=20, verbose_name='Maximum Participants'),
        ),
        migrations.AlterField(
            model_name='corporateprogram',
            name='name',
            field=models.CharField(help_text='Name of the corporate program', max_length=100, verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_corporate_eligible',
            field=models.BooleanField(default=False, help_text='Whether this service is eligible for corporate programs', verbose_name='Is Corporate Eligible'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='name',
            field=models.CharField(help_text='Name of the package', max_length=100, verbose_name='Package Name'),
        ),
    ]
