# Generated by Django 5.0.9 on 2025-02-17 11:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_base_price_service_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage off regular service price', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='price_per_session',
            field=models.DecimalField(decimal_places=2, help_text='Price per session (must be greater than 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per Session'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='validity_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days the package is valid for', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Validity Period'),
        ),
    ]
