# Generated by Django 5.0.9 on 2024-11-28 18:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('locations', '0002_alter_location_contact_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Name of emergency contact', max_length=100, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Phone number of emergency contact', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Emergency Contact Phone')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the client', verbose_name='Notes')),
                ('medical_notes', models.TextField(blank=True, help_text='Important medical information or conditions', verbose_name='Medical Notes')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this client is active. Unselect instead of deleting accounts.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('preferred_location', models.ForeignKey(blank=True, help_text='Preferred location for sessions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_clients', to='locations.location', verbose_name='Preferred Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'permissions': [('view_client_medical', 'Can view client medical information'), ('manage_client_sessions', 'Can manage client sessions')],
            },
        ),
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Notes from the session', verbose_name='Session Notes')),
                ('feedback', models.TextField(blank=True, help_text='Feedback provided by the client', verbose_name='Client Feedback')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Client rating of the session (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Session Rating')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_session', to='bookings.booking', verbose_name='Booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clients.clientprofile', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client Session',
                'verbose_name_plural': 'Client Sessions',
                'ordering': ['-booking__start_time'],
                'permissions': [('can_view_session_notes', 'Can view session notes'), ('can_manage_session_status', 'Can manage session status')],
            },
        ),
    ]
