#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Database connection check
if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

# Wait for postgres
wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30
>&2 echo 'PostgreSQL is available'

# Install node dependencies if needed
if [ -f "/app/package.json" ] && [ ! "$(ls -A /app/node_modules 2>/dev/null)" ]; then
    echo "Installing node dependencies..."
    npm install --no-audit
fi

exec "$@"
