# Generated by Django 5.0.9 on 2024-11-27 13:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_alter_organization_contact_phone'),
        ('wellness_instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Location name', max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('studio', 'Studio'), ('virtual', 'Virtual'), ('onsite', 'On-site')], help_text='Type of location', max_length=20, verbose_name='Type')),
                ('address', models.TextField(blank=True, help_text='Physical address (if applicable)', verbose_name='Address')),
                ('contact_info', models.JSONField(default=dict, help_text='Contact details in JSON format', verbose_name='Contact Information')),
                ('operating_hours', models.JSONField(default=dict, help_text='Operating hours in JSON format', verbose_name='Operating Hours')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum capacity of the location', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity')),
                ('amenities', models.JSONField(blank=True, default=dict, help_text='Available amenities in JSON format', verbose_name='Amenities')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', help_text='Current status of the location', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the location', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('availability_rules', models.JSONField(default=dict, help_text='Instructor availability rules in JSON format', verbose_name='Availability Rules')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary location for this instructor', verbose_name='Is Primary Location')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('temporary', 'Temporary')], default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this instructor at this location', verbose_name='Notes')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_locations', to='wellness_instructors.wellnessinstructor', verbose_name='Instructor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_instructors', to='locations.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Location Instructor',
                'verbose_name_plural': 'Location Instructors',
                'ordering': ['location', 'instructor'],
                'unique_together': {('location', 'instructor')},
            },
        ),
        migrations.CreateModel(
            name='LocationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Price adjustment for this service at this location', max_digits=10, verbose_name='Price Adjustment')),
                ('availability_rules', models.JSONField(default=dict, help_text='Rules for service availability in JSON format', verbose_name='Availability Rules')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this service is currently available at this location', verbose_name='Is Available')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this service at this location', verbose_name='Notes')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_services', to='locations.location', verbose_name='Location')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Location Service',
                'verbose_name_plural': 'Location Services',
                'ordering': ['location', 'service'],
                'unique_together': {('location', 'service')},
            },
        ),
    ]
