# Generated by Django 5.0.9 on 2024-11-27 17:18

import django.db.models.deletion
from django.db import migrations, models

from locations.models import validate_contact_info, validate_operating_hours


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0003_alter_organization_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contact_info',
            field=models.JSONField(default=dict, help_text='Contact details in JSON format', validators=[validate_contact_info], verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='location',
            name='operating_hours',
            field=models.JSONField(default=dict, help_text='Operating hours in JSON format', validators=[validate_operating_hours], verbose_name='Operating Hours'),
        ),
        migrations.AlterField(
            model_name='locationservice',
            name='availability_rules',
            field=models.JSONField(default=dict, help_text='Rules for service availability', verbose_name='Availability Rules'),
        ),
        migrations.AlterField(
            model_name='locationservice',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether this service is currently available at this location', verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='locationservice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='locations.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='locationservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='services.service', verbose_name='Service'),
        ),
    ]
