# Generated by Django 5.0.9 on 2025-02-17 11:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_servicecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationservice',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price adjustment (positive or negative) for this service at this location', max_digits=10, verbose_name='Price Adjustment'),
        ),
    ]
