# Generated by Django 5.0.9 on 2025-02-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_locationservice_price_adjustment'),
        ('wellness_instructors', '0002_session_time_slot'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='locationinstructor',
            index=models.Index(fields=['instructor'], name='locations_l_instruc_7d38bc_idx'),
        ),
        migrations.AddIndex(
            model_name='locationinstructor',
            index=models.Index(fields=['location', 'instructor'], name='locations_l_locatio_6bf54d_idx'),
        ),
        migrations.AddIndex(
            model_name='locationinstructor',
            index=models.Index(fields=['status'], name='locations_l_status_2ead0e_idx'),
        ),
    ]
