# Generated by Django 5.0.9 on 2024-11-28 14:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_alter_location_contact_info_and_more'),
        ('services', '0003_alter_organization_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(help_text='Unique identifier for the booking', max_length=50, unique=True)),
                ('booking_type', models.CharField(choices=[('individual', 'Individual Booking'), ('corporate', 'Corporate Booking'), ('group', 'Group Session')], default='individual', help_text='Type of booking (individual, corporate, or group)', max_length=20)),
                ('start_time', models.DateTimeField(help_text='Start time of the session')),
                ('end_time', models.DateTimeField(help_text='End time of the session')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('refunded', 'Refunded'), ('company_paid', 'Company Paid'), ('free', 'Free')], default='pending', help_text='Current payment status', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Original price of the service', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to this booking', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Final price after discounts', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the booking')),
                ('medical_notes', models.TextField(blank=True, help_text='Any medical conditions or concerns')),
                ('preferences', models.JSONField(default=dict, help_text='Client preferences for this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='User who booked the session', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(help_text='Instructor assigned to this session', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='locations.locationinstructor')),
                ('location', models.ForeignKey(help_text='Location where the session will take place', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='locations.location')),
                ('organization', models.ForeignKey(blank=True, help_text='Corporate organization if this is a corporate booking', null=True, on_delete=django.db.models.deletion.PROTECT, to='services.organization')),
                ('service', models.ForeignKey(help_text='Service being booked', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='locations.locationservice')),
            ],
            options={
                'ordering': ['-start_time'],
                'permissions': [('can_view_all_bookings', 'Can view all bookings'), ('can_manage_bookings', 'Can manage bookings')],
            },
        ),
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of cancellation')),
                ('reason', models.TextField(help_text='Reason for cancellation')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount to be refunded', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('refund_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('refunded', 'Refunded'), ('company_paid', 'Company Paid'), ('free', 'Free')], default='pending', help_text='Status of the refund', max_length=20)),
                ('booking', models.OneToOneField(help_text='The booking that was cancelled', on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='bookings.booking')),
                ('cancelled_by', models.ForeignKey(help_text='User who cancelled the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cancellation_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the package', max_length=100)),
                ('total_sessions', models.PositiveIntegerField(help_text='Total number of sessions in the package')),
                ('used_sessions', models.PositiveIntegerField(default=0, help_text='Number of sessions already used')),
                ('expiry_date', models.DateField(help_text='Date when the package expires')),
                ('price_per_session', models.DecimalField(decimal_places=2, help_text='Price per individual session', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for the package', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True, help_text='Whether this package is currently active')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization if this is a corporate package', null=True, on_delete=django.db.models.deletion.PROTECT, to='services.organization')),
                ('service', models.ForeignKey(help_text='Service included in this package', on_delete=django.db.models.deletion.PROTECT, to='locations.locationservice')),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('corporate_account', 'Corporate Account'), ('insurance', 'Insurance'), ('package', 'Package Credits'), ('cash', 'Cash'), ('free', 'Free Session')], help_text='Method of payment', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='External payment system transaction ID', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('refunded', 'Refunded'), ('company_paid', 'Company Paid'), ('free', 'Free')], default='pending', help_text='Current status of the payment', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of payment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('booking', models.ForeignKey(help_text='The booking this payment is for', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('payer', models.ForeignKey(help_text='User who made the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('payer_organization', models.ForeignKey(blank=True, help_text='Organization making the payment if corporate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.organization')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='bookings_bo_booking_03d631_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_time', 'end_time'], name='bookings_bo_start_t_1c7039_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='bookings_bo_payment_27706e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingcancellation',
            index=models.Index(fields=['cancellation_date'], name='bookings_bo_cancell_622bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingcancellation',
            index=models.Index(fields=['refund_status'], name='bookings_bo_refund__d4d31a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpackage',
            index=models.Index(fields=['expiry_date'], name='bookings_bo_expiry__d2327c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpackage',
            index=models.Index(fields=['active'], name='bookings_bo_active_7d4c19_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpayment',
            index=models.Index(fields=['transaction_id'], name='bookings_bo_transac_286686_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpayment',
            index=models.Index(fields=['payment_date'], name='bookings_bo_payment_b4c6be_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpayment',
            index=models.Index(fields=['status'], name='bookings_bo_status_e58fce_idx'),
        ),
    ]
