# Generated by Django 5.0.9 on 2025-02-17 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('locations', '0004_alter_locationservice_price_adjustment'),
        ('services', '0005_servicepackage_discount_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Package this booking is using, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.bookingpackage'),
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='owner',
            field=models.ForeignKey(help_text='User who owns this package', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the package was purchased'),
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='service_package',
            field=models.ForeignKey(blank=True, help_text='Service package this booking package is based on', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_packages', to='services.servicepackage'),
        ),
        migrations.AddIndex(
            model_name='bookingpackage',
            index=models.Index(fields=['purchase_date'], name='bookings_bo_purchas_072f17_idx'),
        ),
    ]
