# Generated by Django 5.0.9 on 2025-02-19 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_package_bookingpackage_owner_and_more'),
        ('packages', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Package this booking is using, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='packages.package'),
        ),
        migrations.AlterField(
            model_name='bookingpackage',
            name='owner',
            field=models.ForeignKey(help_text='User who owns this package', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_owned_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
