# Generated by Django 5.0.9 on 2025-02-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_package_alter_bookingpackage_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingPackage',
        ),
    ]
