# Generated by Django 5.0.9 on 2026-03-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_add_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_active_booking_per_instructor_time",
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="end_time_after_start_time",
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="total_price_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="bookingpayment",
            name="unique_transaction_id",
        ),
        migrations.RemoveConstraint(
            model_name="bookingpayment",
            name="payment_amount_non_negative",
        ),
        migrations.AlterField(
            model_name="bookingpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("mpesa", "M-Pesa"),
                    ("corporate_account", "Corporate Account"),
                    ("insurance", "Insurance"),
                    ("package", "Package Credits"),
                    ("cash", "Cash"),
                    ("free", "Free Session"),
                ],
                help_text="Method of payment",
                max_length=20,
            ),
        ),
    ]
