# Generated by Django 5.0.9 on 2024-11-25 13:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('bio', models.TextField(blank=True, help_text='A brief introduction about the instructor', max_length=1000, verbose_name='Biography')),
                ('specializations', models.CharField(choices=[('flexibility', 'Flexibility Training'), ('recovery', 'Recovery & Rehabilitation'), ('sports', 'Sports Performance'), ('general', 'General Wellness'), ('therapeutic', 'Therapeutic Stretching')], default='general', help_text='Primary area of expertise', max_length=20, verbose_name='Specializations')),
                ('certification_level', models.CharField(choices=[('certified', 'Certified Professional'), ('advanced', 'Advanced Certification'), ('specialist', 'Specialist Certification'), ('master', 'Master Instructor')], default='certified', help_text='Current certification level', max_length=20, verbose_name='Certification Level')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0, help_text='Years of professional experience', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Years of Experience')),
                ('is_available', models.BooleanField(default=True, help_text='Indicates if the instructor is currently accepting new clients', verbose_name='Is Available')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Standard hourly rate for sessions', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hourly Rate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_instructor', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Stretch Instructor',
                'verbose_name_plural': 'Wellness Instructors',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Name or title of the session', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the session', verbose_name='Description')),
                ('session_type', models.CharField(choices=[('one_on_one', 'One-on-One'), ('group', 'Group Session'), ('workshop', 'Workshop')], default='one_on_one', max_length=20, verbose_name='Session Type')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all_levels', max_length=20, verbose_name='Difficulty Level')),
                ('duration', models.PositiveSmallIntegerField(default=60, help_text='Session duration in minutes', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)], verbose_name='Duration (minutes)')),
                ('max_participants', models.PositiveSmallIntegerField(default=1, help_text='Maximum number of participants allowed', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Maximum Participants')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per session', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this session is currently being offered', verbose_name='Active')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='wellness_instructors.wellnessinstructor', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['instructor', 'session_type'], name='stretch_ins_instruc_951c42_idx'), models.Index(fields=['is_active', 'difficulty_level'], name='stretch_ins_is_acti_b0b7f3_idx')],
            },
        ),
    ]
