# Generated by Django 5.0.9 on 2024-12-06 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_blackoutdate_instructor'),
        ('wellness_instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='schedules.timeslot', verbose_name='Time Slot'),
        ),
    ]
