# Generated by Django 5.0.9 on 2026-03-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wellness_instructors", "0002_session_time_slot"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="session",
            new_name="wellness_in_instruc_007cd9_idx",
            old_name="stretch_ins_instruc_951c42_idx",
        ),
        migrations.RenameIndex(
            model_name="session",
            new_name="wellness_in_is_acti_b97fd6_idx",
            old_name="stretch_ins_is_acti_b0b7f3_idx",
        ),
    ]
