# Generated by Django 5.0.9 on 2024-11-25 20:13

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wellness_instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week for this schedule', verbose_name='Day of Week')),
                ('start_time', models.TimeField(help_text='Start time for this schedule', verbose_name='Start Time')),
                ('end_time', models.TimeField(help_text='End time for this schedule', verbose_name='End Time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active', verbose_name='Active')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='wellness_instructors.wellnessinstructor', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_datetime', models.DateTimeField(help_text='Start time for this slot', verbose_name='Start Time')),
                ('end_datetime', models.DateTimeField(help_text='End time for this slot', verbose_name='End Time')),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='available', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this time slot', verbose_name='Notes')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='schedules.schedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateTimeField(help_text='Start of unavailability period', verbose_name='Start Date')),
                ('end_date', models.DateTimeField(help_text='End of unavailability period', verbose_name='End Date')),
                ('reason', models.CharField(help_text='Reason for unavailability', max_length=200, verbose_name='Reason')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this blackout date repeats yearly (e.g., holidays)', verbose_name='Recurring')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackout_dates', to='wellness_instructors.wellnessinstructor', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Blackout Date',
                'verbose_name_plural': 'Blackout Dates',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['instructor', 'start_date'], name='schedules_b_instruc_5569d5_idx'), models.Index(fields=['is_recurring'], name='schedules_b_is_recu_3b1359_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('instructor', 'weekday', 'start_time'), name='unique_instructor_weekday_start'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['start_datetime', 'status'], name='schedules_t_start_d_32d459_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['schedule', 'status'], name='schedules_t_schedul_1ce345_idx'),
        ),
    ]
