# Generated by Django 5.0.9 on 2024-11-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('wellness_instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackoutdate',
            name='instructor',
            field=models.ForeignKey(help_text='The instructor who is unavailable', on_delete=django.db.models.deletion.CASCADE, related_name='blackout_dates', to='wellness_instructors.wellnessinstructor', verbose_name='Instructor'),
        ),
    ]
